"""empty message

Revision ID: 00c0d82ab78b
Revises: 
Create Date: 2019-11-03 17:28:25.714561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00c0d82ab78b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grade',
    sa.Column('g_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('g_name', sa.String(length=20), nullable=True),
    sa.Column('g_create_time', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('g_id'),
    sa.UniqueConstraint('g_name')
    )
    op.create_table('permisstion',
    sa.Column('p_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('p_name', sa.String(length=20), nullable=True),
    sa.Column('p_er', sa.String(length=20), nullable=True),
    sa.Column('p_create_time', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('p_id'),
    sa.UniqueConstraint('p_er'),
    sa.UniqueConstraint('p_name')
    )
    op.create_table('role',
    sa.Column('r_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('r_name', sa.String(length=100), nullable=True),
    sa.Column('r_create_time', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('r_id'),
    sa.UniqueConstraint('r_name')
    )
    op.create_table('r_p',
    sa.Column('r_id', sa.Integer(), nullable=False),
    sa.Column('p_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['p_id'], ['permisstion.p_id'], ),
    sa.ForeignKeyConstraint(['r_id'], ['role.r_id'], ),
    sa.PrimaryKeyConstraint('r_id', 'p_id')
    )
    op.create_table('student',
    sa.Column('s_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('s_name', sa.String(length=20), nullable=True),
    sa.Column('s_sex', sa.Integer(), nullable=True),
    sa.Column('grade_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['grade_id'], ['grade.g_id'], ),
    sa.PrimaryKeyConstraint('s_id')
    )
    op.create_table('user',
    sa.Column('u_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('u_name', sa.String(length=16), nullable=True),
    sa.Column('u_password', sa.String(length=200), nullable=True),
    sa.Column('u_create_time', sa.DATETIME(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.r_id'], ),
    sa.PrimaryKeyConstraint('u_id'),
    sa.UniqueConstraint('u_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('student')
    op.drop_table('r_p')
    op.drop_table('role')
    op.drop_table('permisstion')
    op.drop_table('grade')
    # ### end Alembic commands ###
